const languages = {
    "zh-CN": {
      "title": "LearnCode|项目驱动,需求为上的编程学习平台",
      "startLearning": "开始学习",
      "target": "项目驱动  需求为上",
      "slogan": "远离刷题痛苦，用实际需求点燃编程学习的动力",
      "subtitle": "从零开始，掌握全新编程语言",
      "description": "项目实战 | 内嵌编辑器 | 在线调试 | 逐步引导",
      "projectDriven": "需求导向学习",
      "projectDescription": "通过实际需求学习，将理论知识以应用于实践中",
      "onlineEnv": "在线开发环境",
      "onlineEnvDescription": "内嵌终端和在线调试工具，随时随地编写和测试代码",
      "detailedGuide": "详细注释引导",
      "detailedGuideDescription": "逐步引导，详尽注释，助你轻松完成每个项目",
      "searchplaceholder": "请输入",
      "search": "搜索",
      "programmingLanguages": "编程语言",
      "databases": "数据库",
      "toolkits": "工具库",
      "machineLearning": "机器学习",
      "deepLearning": "深度学习",
      "AIModels": "AI大模型",
      "Web3": "Web3",
      "other": "其他",
      "contributedoc": "贡献文档"
    },
    "en": {
      "title": "LearnCode|Project-driven, Needs-first coding platform",
      "startLearning": "Start Learning",
      "target": "Project-Driven  Needs-First",
      "slogan": "Avoid rote problem-solving pain, Fuel coding motivation with real needs",
      "subtitle": "Master new programming languages from scratch",
      "description": "Project-based | Built-in Editor | Online Debugging | Step-by-step Guidance",
      "projectDriven": "Needs-First Learning",
      "projectDescription": "Learn through actual requirements, apply theoretical knowledge to practice",
      "onlineEnv": "Online Development Environment",
      "onlineEnvDescription": "Built-in terminal and online debugging tools, code and test anytime, anywhere",
      "detailedGuide": "Detailed Commentary Guidance",
      "detailedGuideDescription": "Step-by-step guidance with detailed comments to help you complete each project easily",
      "searchplaceholder": "Please enter",
      "search": "Search",
      "programmingLanguages": "Programming Languages",
      "databases": "Databases",
      "toolkits": "Toolkits",
      "machineLearning": "Machine Learning",
      "deepLearning": "Deep Learning",
      "AIModels": "AI Models",
      "Web3": "Web3",
      "other": "Other",
      "contributedoc": "Contribute Document"
    }
  };
// 把下面的 HTML 内容中的中文部分提取出来，放到 docuLanguages 中，像上面的 languages 一样，把中文部分和英文部分分别放到 "zh-CN" 和 "en" 中。

